### ISSUE TITLE
Hashes in data URIs are being stored as hex encoded strings

### ISSUE THREAD

**Issue by libertylocked** [ConsenSys/Linnia-Smart-Contracts#45]
Hash like `0x59742369c54039d5611d84452aa6c31b72da336b76ed4029b12c3dc5479836ba` is stored as a literal string that starts with `0x`, 66 bytes in total. inb4 they are 32 bytes

Also is `0x` a legal data URI? Or `0x000000000000000000000000000000000000000000000000000000000000`

**Comment by libertylocked** [comment]
also storage is quadrupled as it now requires 4 words

**Comment by godfreyhobbs** [comment]
This change is not needed at this point in the project. There is no need to optimize gas or storage until we are ready to go to mainnet, then we will likely use something like CID.

**Comment by libertylocked** [comment]
The point isn't optimization. This is a huge hack and is just insanity. I don't know how you will gain any respect from the community if the contract is all hacks. Anti patterns should never be used in any engineering product.

**Comment by libertylocked** [comment]
If this is how low you want to set the bar, close this issue and be happy with your hacks
