### ISSUE TITLE
CircleCI configuration must be updated

### ISSUE THREAD

**Issue by cleishm** [ConsenSys/Linnia-Smart-Contracts#57]
CircleCI is currently warning that support for the 1.0 style configuration will end on August 31st, 2018. At this point, builds for this project will fail unless the configuration is updated.

Migration documentation is available here: https://circleci.com/docs/2.0/migration/

**Comment by godfreyhobbs** [comment]
Thanks, @cleishm we have that on our backlog.

**Comment by cleishm** [comment]
Sweet. Let me know if you need a hand.

**Comment by godfreyhobbs** [comment]
In progress

**Comment by godfreyhobbs** [comment]
#59 is ready for review
